version: '2.1'
executors:
  php7-2:
    docker:
      - image: php:7.2-alpine
  php7-3:
    docker:
      - image: php:7.3-alpine
  php7-4:
    docker:
      - image: php:7.4-alpine

jobs:
  composer:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: Install alpine requirements for checkout
          command: apk add git openssh-client curl
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
      - run:
          name: composer
          command: |
            if [[ ! -f vendor/autoload.php ]]; then
                curl https://getcomposer.org/composer-stable.phar --location --silent  --output /usr/bin/composer; \
                chmod +x /usr/bin/composer; \
                composer install --no-progress --no-interaction; \
            fi
      - save_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  phpcs:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpcs
          command: vendor/bin/phpcs -n

  phpstan:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpstan
          command: vendor/bin/phpstan analyse

  phpunit:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: phpunit
          command: vendor/bin/phpunit --testdox

workflows:
  all-tests:
    jobs:
      - composer:
          matrix:
            parameters:
              executor: [php7-2, php7-3, php7-4]
      - phpcs:
          requires:
            - composer
          matrix:
            parameters:
              executor: [php7-2, php7-3, php7-4]
      - phpstan:
          requires:
            - composer
          matrix:
            parameters:
              executor: [php7-2, php7-3, php7-4]
      - phpunit:
          requires:
            - composer
          matrix:
            parameters:
              executor: [php7-2, php7-3, php7-4]